version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-books"
s3_bucket = "lambda-books-master-cloud-apps"
s3_prefix = "lambda-books"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"